# Generated by Django 3.2.16 on 2022-11-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='name',
            new_name='articles',
        ),
    ]
